### ISSUE TITLE
Submit resource for translation

### ISSUE THREAD

**Issue by nirnaeth** [tmaesaka/transifex-ruby#9]
Since I'll need to implement this anyway for the work I'm doing, I'd like to propose to add a `push_content` method to `Transifex::Resource` that would implement the `PUT` method on the endpoint described [here](https://docs.transifex.com/api/resources#uploading-and-downloading-translations).

I know the client is supposed to be simple, this shouldn't mess things too much. 

What do you think?

**Comment by JasonBarnabe** [comment]
I would personally not use it as I use webhooks to perform this, but I have no objection to the functionality if you develop and test it.
